#!/bin/bash

# b49 before 9
echo -e "\t\t****b49****"

# count down
# show countdown till 9AM, if after 9 then 24h till next WEEKDAY 9
time_now=$(date +%H%M)
if [ $time_now -gt 900 ]
	then
		echo "post 9"
fi
timeM=$(($(date +%H) * 60 + $(date +%M)))
#echo "$timeM"
dayM=1440
timeR=$(($dayM - $timeM + 900))
#echo "$timeR"
#mins to 9 so 
countH=$(($timeR / 60))
countM=$(($timeR % 60))
echo "$countH HOURS :: $countM  Mins togo"







# 6hours/ 360m fast
